batch_size: 1
data_augmentation_options:
  - random_horizontal_flip: {}
optimizer:
  momentum_optimizer:
    learning_rate:
      manual_step_learning_rate:
        initial_learning_rate: 0.0003
        schedule:
          - step: 900000
            learning_rate: .00003
          - step: 1200000
            learning_rate: .000003
    momentum_optimizer_value: 0.9
  use_moving_average: false
gradient_clipping_by_norm: 10.0
fine_tune_checkpoint: "checkpoint/model.ckpt"
from_detection_checkpoint: true
num_steps: 200000
load_all_detection_checkpoint_vars: true
